<?php

/**
 * @var Olelukoie_News_Block_Item
 */
?>

<?php $_newsItem = $this->helper('olelukoie_news')->getNewsItemInstance(); ?>

<div id="news_item_messages">
    <?php echo $this->getMessageBlock()->getGroupedHtml() ?>
</div>

<div>
    <h1><?php echo $this->escapedHtml($_newsItem->getTitle()) ?></h1>

    <div>
        <?php echo $this->formatDate($_newsItem->getTimePublished(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM) ?> | <?php echo $this->escapedHtml($_newsItem->getAuthor()) ?>
    </div>

    <div>
        <?php if ($imageUrl = $this->getImageUrl($_newsItem, 400)): ?>
            <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_newsItem->getTitle()) ?>>" /></p>
        <?php endif; ?>

        <div>
            <?php echo $this->escapedHtml($_newsItem->getAuthor()) ?>
        </div>
    </div>

    <div>
        <?php echo $_newsItem->getContent() ?>
    </div>

    <div>
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo Mage::helper('olelukoie_news')->__('Return to list') ?>
        </a>
    </div>
</div>

