<?php

/**
 * @var Olelukoie_News_Block_List $this
 */
?>

<div id="news_list_message">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div>
    <h1><?php echo Mage::helper('olelukoie_news')->__('sites News') ?></h1>
</div>

<div>
    <?php foreach ($this->getCollection() as $newsItem): ?>
        <div id="item_<?php echo $newsItem->getId() ?>">
            <h2>
                <a href="<?php echo $this->getImageUrl($newsItem, 400) ?>">
                    <?php echo $this->escapeHtml($newsItem->getTitle()) ?>
                </a>
            </h2>

            <div>
                <?php echo $this->formatDate($newsItem->getTimePublished(), 'medium') ?> | <?php echo $this->escapeHtml($newsItem->getAuthor()) ?>
            </div>

            <?php if ($imageUrl = $this->getImageUrl($newsItem, 100)): ?>
                <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($newsItem->getTitle()) ?>"></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>

<?php echo $this->getPager() ?>


